name: dough
description: A novel currency converter app for Android and iOS.

version: 1.0.0

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.7
  equatable: ^1.1.1
  http: ^0.12.0+4
  shared_preferences: ^0.5.6+3
  get_it: ^4.0.1
  provider: ^4.0.5
  flutter_neumorphic: ^2.1.0+1
  flutter_circular_slider: ^2.5.0
  url_launcher: ^5.4.10
 
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.5
  mockito: ^4.1.1
  
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # assets:
    #- assets/images/dough-icon.png
    #- assets/images/2.0x/dough-icon.png
    #- assets/images/3.0x/dough-icon.png

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/NotoSans-Italic.ttf
          style: italic
          weight: 400

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/icon/dough-ios-icon.png"
  image_path_android: "assets/icon/dough-android-icon.png"
  adaptive_icon_background: "assets/icon/dough-android-adaptive-icon-background.png"
  adaptive_icon_foreground: "assets/icon/dough-android-adaptive-icon-foreground.png"




 
